### ISSUE TITLE
Problems also on PC in Safari

### ISSUE THREAD

**Issue by lajanda** [bast/twirll-prototype#26]
I suggested that a colleague who is learning Russian should try the SMARTool. She has a PC (not Mac) and she was using Safari. The search by Topics worked, but the other two options did not work.

**Comment by bast** [comment]
Related to #24. I will try to reproduce it.

**Comment by bast** [comment]
It is difficult for me to reproduce it since I have neither good access to a Windows nor to an macOS. And on Linux there is no Safari. There is the "sister browser" Konqueror but there I don't see the problem. It would be great if we one day can sit together and test it out on one of these machines and then I can have a look.

**Comment by bast** [comment]
From #24: Search by dictionary function does not work when used in Safari but it works fine on Chrome.

**Comment by lajanda** [comment]
Sorry, Radovan, I didn’t realize that. This week is pretty crazy. Maybe next week I can come over and show you the Safari issue?

**Comment by bast** [comment]
Yes - no rush from my side. It will be useful if we check it together once things calm down.

**Comment by bast** [comment]
Fixed in 7fc52132d4eb6c8a1066e2c3387e401b9e85e987.
